### ISSUE TITLE
Generic Runtime rework

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-pipeline#200]
The current production system generates jobs only for LAVA labs.  However, we need to make this more generic and the new pipeline implementation already generates jobs that can run either in a local shell or in Kubernetes.  We now need to rework this to have a common way to generate job definitions that works for any runtime.

- [x] https://github.com/kernelci/kernelci-core/issues/1725
  - [x] kernelci/kernelci-core#1726
  - [x] kernelci/kernelci-core#1729
  - [x] `kernelci.test` marked as legacy code and stays available until the current pipeline is phased out
- [x] Job generation and submission
  - [x] kernelci/kernelci-core#1728
  - [x] kernelci/kernelci-pipeline#207
- [x] https://github.com/kernelci/kernelci-core/issues/1541
- [x] #209

~~Limitations: For now, one can assume that the input data will need to match the expected templates for the target runtime.  So LAVA jobs will require bmeta.json until builds are added to the new API, and shell / k8s jobs such as kver and KUnit will require a tarball node (either an ID or the dumped JSON data).~~
UPDATE: It's more useful to first get support in place for builds and look into adding LAVA as a follow-up.

**Comment by gctucker** [comment]
Some follow-up work is still needed to manage the build data with a model but that's not part of this issue any more.  We can already run builds and use the binaries to run tests in LAVA which is what this was all about.  So it can now be closed.
