### ISSUE TITLE
API abstraction in kernelci-core

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-pipeline#202]
The kernelci-core `Database` abstraction layer needs to be deprecated in order to make the code focus only on the new API.

- [ ] `kernelci.db` code deprecated and moved to `kernelci.legacy` until old backend is phased out
- [ ] `kernelci.api` used with new `kci` tool and related `kernelci.config.api`
- [ ] `kci user` commands implemented to make use of the API and manage tokens etc.
