### ISSUE TITLE
Kernel build support

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-pipeline#203]
Doing kernel builds with the new API & Pipeline should be done using Jinja2 job templates and scheduled like the `kver` and `kunit` tests either in a `shell` or `k8s` runtime environment (and potentially `docker`).

- [x] https://github.com/kernelci/kernelci-core/issues/1541
  - [x] verified locally with `shell` runtime
  - [x] base node object sent with build result and artifacts uploaded to storage
  - [x] child nodes sent for each build step (config, image, modules, dtbs, kselftest...) with their logs and artifacts
- [x] https://github.com/kernelci/kernelci-api/issues/39

Follow-up development for the kernel build data model is now covered by #277.
