### ISSUE TITLE
Additional meta-data populated for build nodes

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-pipeline#275]
Once the schema for build nodes has been added to the API, the build jobs should be updated to send the additional meta-data (defconfig, architecture, compiler...)

- [ ] build job templates updated to populate extra meta-data
- [ ] child nodes all use the build step schema
- [ ] tested locally with `shell` runtime
- [ ] tested on staging with `k8s` runtime
