### ISSUE TITLE
Add kbuild data model

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-pipeline#277]
Now that the initial pipeline implementation supports running kernel builds, we should consider adding a data model for it.  The current data is stored in `Node.data` but the field are not specified anywhere.  As a starting point, the `kbuild.jinja2` job template adds the following entries to the data dictionary: arch, defconfig, compiler, fragments.

- [ ] kernelci/kernelci-pipeline#275
  - [ ] verified locally with `shell` and `k8s` runtimes
  - [ ] verified on staging with `k8s` runtime
- [x] https://github.com/kernelci/kernelci-api/issues/37

**Comment by gctucker** [comment]
Reassigning to @nuclearcat who is working on kbuild now.
