### ISSUE TITLE
Email reports

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-pipeline#35]
Now that we have basic support for generating reports, the next step is to include test results and actually send emails to the `kernelci-results-staging` mailing list. This includes several sub-tasks:

* Extend template to replicate what is currently being sent by `kernelci-backend`
* Listen to events that signal that all tests have been either run or have timed out for a given kernel revision
* Add details for regressions in the email report

> Note: The last 2 points rely on some missing features on the API side, to have regressions tracked in the database and to have events sent when all the tests for a given kernel revision have transitioned from Pending to either a pass/fail result or timed out. It also relies on the API to detect when a pending test times out.

Subtaks checklist

- [x] https://github.com/kernelci/kernelci-pipeline/issues/38
- [x] ~~https://github.com/kernelci/kernelci-pipeline/issues/64~~
- [ ] Email report content
  - [x] #279
  - [x] #280
  - [x] #281
- [ ] Email report functionality
  - [x] #282
  - [x] #283

**Comment by gctucker** [comment]
The checklist markup syntax is `- [ ] `

**Comment by nuclearcat** [comment]
Closing as superseded. The pipeline-local email and test-report service described here was removed; reporting now flows through KCIDB and auxiliary reporting tools. See [127814e](https://github.com/kernelci/kernelci-pipeline/commit/127814e) and the current [KCIDB bridge](https://github.com/kernelci/kernelci-pipeline/blob/main/src/kcidb_bridge.py).
